services:
  web:
    image: web
    build:
      context: .
      dockerfile: Web/Dockerfile

  application:
    image: application 
    build:
      context: .
      dockerfile: Application/Dockerfile

